<?php

use App\Http\Controllers\Api\ApiTokenController;
use App\Http\Controllers\Api\AppConfigController;
use App\Http\Controllers\Api\BalanceImportController;
use App\Http\Controllers\Api\CollectorApiController;
use App\Http\Controllers\Api\CollectorPaymentController;
use App\Http\Controllers\Api\CollectorSyncController;
use App\Http\Controllers\Api\CustomerApiController;
use App\Http\Controllers\Api\CustomerImportController;
use App\Http\Controllers\Api\EquipmentImportController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\InvoiceApiController;
use App\Http\Controllers\Api\MessageWebhookController;
use App\Http\Controllers\Api\NetworkCommandController;
use App\Http\Controllers\Api\PartnerApiController;
use App\Http\Controllers\Api\PaymentApiController;
use App\Http\Controllers\Api\PaymentGatewayWebhookController;
use App\Http\Controllers\Api\PlanApiController;
use App\Http\Controllers\Api\PlanImportController;
use App\Http\Controllers\Api\PortalAuthController;
use App\Http\Controllers\Api\PortalBillingController;
use App\Http\Controllers\Api\PortalController;
use App\Http\Controllers\Api\PortalTicketController;
use App\Http\Controllers\Api\PublicBillingPaymentController;
use App\Http\Controllers\Api\RouterApiController;
use App\Http\Controllers\Api\RouterSubscriberImportController;
use App\Http\Controllers\Api\ServiceApiController;
use App\Http\Controllers\Api\ServiceImportController;
use App\Http\Controllers\Api\TechnicianMediaController;
use App\Http\Controllers\Api\TechnicianWorkOrderController;
use App\Http\Controllers\Api\TicketApiController;
use App\Http\Controllers\Api\WhishPaymentCallbackController;
use App\Http\Controllers\Api\WorkOrderApiController;
use App\Http\Controllers\Api\ZoneApiController;
use App\Http\Middleware\ApiResponseHeaders;
use App\Models\User;
use App\Support\Api\UserApiResource;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware(ApiResponseHeaders::class)->group(function (): void {
    Route::get('/health', [HealthController::class, 'show'])->name('api.health');
    Route::post('/public-billing/{token}/stripe-intent', [PublicBillingPaymentController::class, 'stripe'])->middleware('throttle:20,1')->name('api.public-billing.stripe');
    Route::post('/public-billing/{token}/whish', [PublicBillingPaymentController::class, 'whish'])->middleware('throttle:20,1')->name('api.public-billing.whish');
    Route::get('/public-billing/{token}/whish/{attempt}', [PublicBillingPaymentController::class, 'whishStatus'])->middleware('throttle:30,1')->name('api.public-billing.whish.status');
    Route::post('/webhooks/gateways/{gateway}', MessageWebhookController::class)->name('api.webhooks.gateways');
    Route::post('/webhooks/payments/{gateway}', PaymentGatewayWebhookController::class)->name('api.webhooks.payments');
    Route::get('/webhooks/payments/whish/success', [WhishPaymentCallbackController::class, 'success'])->middleware('throttle:30,1')->name('api.webhooks.payments.whish.success');
    Route::get('/webhooks/payments/whish/failure', [WhishPaymentCallbackController::class, 'failure'])->middleware('throttle:30,1')->name('api.webhooks.payments.whish.failure');
    Route::post('/tokens', [ApiTokenController::class, 'store'])->middleware('throttle:login')->name('api.tokens.store');
    Route::post('/auth/staff/login', [ApiTokenController::class, 'staffLogin'])->middleware('throttle:login')->name('api.auth.staff.login');
    Route::post('/auth/staff/two-factor', [ApiTokenController::class, 'staffTwoFactor'])->middleware('throttle:login')->name('api.auth.staff.two-factor');
    Route::prefix('auth/customer')->middleware('portal.tenant.request')->group(function (): void {
        Route::post('/otp/request', [PortalAuthController::class, 'requestCustomerOtp'])->middleware('throttle:customer-otp')->name('api.auth.customer.otp.request');
        Route::post('/otp/verify', [PortalAuthController::class, 'verifyCustomerOtp'])->middleware('throttle:login')->name('api.auth.customer.otp.verify');
    });
    Route::post('/auth/customer/logout', [PortalAuthController::class, 'logout'])->middleware('portal.auth')->name('api.auth.customer.logout');
    Route::prefix('portal/{tenant:slug}')->middleware('portal.tenant')->group(function (): void {
        Route::post('/otp/request', [PortalAuthController::class, 'requestOtp'])->middleware('throttle:customer-otp')->name('api.portal.otp.request');
        Route::post('/otp/verify', [PortalAuthController::class, 'verifyOtp'])->middleware('throttle:login')->name('api.portal.otp.verify');
        Route::post('/logout', [PortalAuthController::class, 'logout'])->middleware('portal.auth')->name('api.portal.logout');
        Route::get('/me', [PortalController::class, 'me'])->middleware('portal.auth')->name('api.portal.me');
        Route::get('/me/profile', [PortalController::class, 'me'])->middleware('portal.auth')->name('api.portal.profile');
        Route::patch('/me/profile', [PortalController::class, 'updateProfile'])->middleware('portal.auth')->name('api.portal.profile.update');
        Route::get('/me/services', [PortalController::class, 'services'])->middleware('portal.auth')->name('api.portal.services');
        Route::get('/me/services/{service}/usage', [PortalController::class, 'usage'])->middleware('portal.auth')->name('api.portal.services.usage');
        Route::post('/me/services/{service}/restart-session', [PortalController::class, 'restartSession'])->middleware(['portal.auth', 'idempotency'])->name('api.portal.services.restart');
        Route::get('/me/notices', [PortalController::class, 'notices'])->middleware('portal.auth')->name('api.portal.notices');
        Route::get('/me/tickets', [PortalTicketController::class, 'index'])->middleware('portal.auth')->name('api.portal.tickets.index');
        Route::post('/me/tickets', [PortalTicketController::class, 'store'])->middleware('portal.auth')->name('api.portal.tickets.store');
        Route::get('/me/tickets/{ticket}', [PortalTicketController::class, 'show'])->middleware('portal.auth')->name('api.portal.tickets.show');
        Route::post('/me/tickets/{ticket}/messages', [PortalTicketController::class, 'message'])->middleware('portal.auth')->name('api.portal.tickets.messages');
        Route::post('/me/tickets/{ticket}/rating', [PortalTicketController::class, 'rating'])->middleware('portal.auth')->name('api.portal.tickets.rating');
        Route::get('/billing', [PortalBillingController::class, 'show'])->middleware('portal.auth')->name('api.portal.billing');
        Route::get('/me/balance', [PortalBillingController::class, 'balance'])->middleware('portal.auth')->name('api.portal.balance');
        Route::get('/me/invoices', [PortalBillingController::class, 'invoices'])->middleware('portal.auth')->name('api.portal.invoices');
        Route::get('/me/invoices/{invoice}/pdf', [PortalBillingController::class, 'invoicePdf'])->middleware('portal.auth')->name('api.portal.invoices.pdf');
        Route::get('/me/invoices/{invoice}', [PortalBillingController::class, 'invoice'])->middleware('portal.auth')->name('api.portal.invoices.show');
        Route::get('/me/payments', [PortalBillingController::class, 'payments'])->middleware('portal.auth')->name('api.portal.payments');
        Route::post('/payments/intent', [PortalBillingController::class, 'intent'])->middleware(['portal.auth', 'idempotency'])->name('api.portal.payments.intent');
        Route::post('/me/payments/intent', [PortalBillingController::class, 'intent'])->middleware(['portal.auth', 'idempotency'])->name('api.portal.me.payments.intent');
    });

    Route::middleware('portal.auth')->group(function (): void {
        Route::get('/me/profile', [PortalController::class, 'me'])->name('api.customer.profile');
        Route::patch('/me/profile', [PortalController::class, 'updateProfile'])->name('api.customer.profile.update');
        Route::get('/me/services', [PortalController::class, 'services'])->name('api.customer.services');
        Route::get('/me/services/{service}/usage', [PortalController::class, 'usageRoot'])->name('api.customer.services.usage');
        Route::post('/me/services/{service}/restart-session', [PortalController::class, 'restartSessionRoot'])->middleware('idempotency')->name('api.customer.services.restart');
        Route::get('/me/notices', [PortalController::class, 'notices'])->name('api.customer.notices');
        Route::get('/me/tickets', [PortalTicketController::class, 'index'])->name('api.customer.tickets.index');
        Route::post('/me/tickets', [PortalTicketController::class, 'store'])->name('api.customer.tickets.store');
        Route::get('/me/tickets/{ticket}', [PortalTicketController::class, 'showRoot'])->name('api.customer.tickets.show');
        Route::post('/me/tickets/{ticket}/messages', [PortalTicketController::class, 'messageRoot'])->name('api.customer.tickets.messages');
        Route::post('/me/tickets/{ticket}/rating', [PortalTicketController::class, 'ratingRoot'])->name('api.customer.tickets.rating');
        Route::get('/me/balance', [PortalBillingController::class, 'balance'])->name('api.customer.balance');
        Route::get('/me/invoices', [PortalBillingController::class, 'invoices'])->name('api.customer.invoices');
        Route::get('/me/invoices/{invoice}/pdf', [PortalBillingController::class, 'invoicePdfRoot'])->name('api.customer.invoices.pdf');
        Route::get('/me/invoices/{invoice}', [PortalBillingController::class, 'invoiceRoot'])->name('api.customer.invoices.show');
        Route::get('/me/payments', [PortalBillingController::class, 'payments'])->name('api.customer.payments');
        Route::post('/me/payments/intent', [PortalBillingController::class, 'intent'])->middleware('idempotency')->name('api.customer.payments.intent');
    });

    Route::middleware(['auth:sanctum', 'tenant'])->group(function (): void {
        Route::delete('/tokens/current', [ApiTokenController::class, 'destroy'])->name('api.tokens.destroy');
        Route::post('/auth/logout', [ApiTokenController::class, 'destroy'])->name('api.auth.logout');
        Route::get('/auth/me', [ApiTokenController::class, 'me'])->name('api.auth.me');
        Route::post('/auth/devices/{device}/revoke', [ApiTokenController::class, 'revokeDevice'])->name('api.auth.devices.revoke');
        Route::post('/auth/push-token', [ApiTokenController::class, 'pushToken'])->name('api.auth.push-token');
        Route::get('/app/config', [AppConfigController::class, 'show'])->name('api.app.config');
        Route::get('/me', function (Request $request, UserApiResource $resource) {
            $user = $request->user();
            abort_unless($user instanceof User, 401);

            return response()->json($resource->make($user));
        })->name('api.me');
        Route::middleware('any-abilities:staff:operator,staff:collector,staff:technician')->group(function (): void {
            Route::get('/customers', [CustomerApiController::class, 'index'])->name('api.customers.index');
            Route::get('/customers/{customer:public_id}', [CustomerApiController::class, 'show'])->name('api.customers.show');
            Route::get('/zones', [ZoneApiController::class, 'index'])->name('api.zones.index');
            Route::get('/zones/{zone}', [ZoneApiController::class, 'show'])->name('api.zones.show');
            Route::get('/services', [ServiceApiController::class, 'index'])->name('api.services.index');
            Route::get('/services/{service}', [ServiceApiController::class, 'show'])->name('api.services.show');
            Route::get('/plans', [PlanApiController::class, 'index'])->name('api.plans.index');
            Route::get('/plans/{plan}', [PlanApiController::class, 'show'])->name('api.plans.show');
            Route::get('/invoices', [InvoiceApiController::class, 'index'])->name('api.invoices.index');
            Route::get('/invoices/{invoice}', [InvoiceApiController::class, 'show'])->name('api.invoices.show');
            Route::get('/tickets', [TicketApiController::class, 'index'])->name('api.tickets.index');
            Route::get('/tickets/{ticket}', [TicketApiController::class, 'show'])->name('api.tickets.show');
            Route::get('/routers', [RouterApiController::class, 'index'])->name('api.routers.index');
            Route::get('/routers/{router}', [RouterApiController::class, 'show'])->name('api.routers.show');
            Route::get('/payments', [PaymentApiController::class, 'index'])->name('api.payments.index');
            Route::get('/payments/{payment}', [PaymentApiController::class, 'show'])->name('api.payments.show');
            Route::get('/work-orders', [WorkOrderApiController::class, 'index'])->name('api.work-orders.index');
            Route::get('/work-orders/{workOrder}', [WorkOrderApiController::class, 'show'])->name('api.work-orders.show');
            Route::get('/services/{service}/network-commands', [ServiceApiController::class, 'networkCommands'])->name('api.services.network-commands');
            Route::post('/services/{service}/plan-change-previews', [ServiceApiController::class, 'planChangePreview'])->name('api.services.plan-change-previews');
            Route::post('/payments', [PaymentApiController::class, 'store'])->middleware('idempotency')->name('api.payments.store');
        });
        Route::middleware('abilities:staff:operator')->group(function (): void {
            Route::post('/customers', [CustomerApiController::class, 'store'])->name('api.customers.store');
            Route::patch('/customers/{customer:public_id}', [CustomerApiController::class, 'update'])->name('api.customers.update');
            Route::post('/services', [ServiceApiController::class, 'store'])->name('api.services.store');
            Route::post('/tickets', [TicketApiController::class, 'store'])->name('api.tickets.store');
            Route::post('/tickets/{ticket}/messages', [TicketApiController::class, 'message'])->name('api.tickets.messages');
            Route::post('/tickets/{ticket}/status', [TicketApiController::class, 'status'])->name('api.tickets.status');
            Route::post('/routers', [RouterApiController::class, 'store'])->name('api.routers.store');
            Route::post('/services/{service}/activate', [ServiceApiController::class, 'activate'])->middleware('idempotency')->name('api.services.activate');
            Route::post('/services/{service}/suspend', [ServiceApiController::class, 'suspend'])->middleware('idempotency')->name('api.services.suspend');
            Route::post('/services/{service}/pause', [ServiceApiController::class, 'pause'])->middleware('idempotency')->name('api.services.pause');
            Route::post('/services/{service}/resume', [ServiceApiController::class, 'resume'])->middleware('idempotency')->name('api.services.resume');
            Route::post('/services/{service}/terminate', [ServiceApiController::class, 'terminate'])->middleware('idempotency')->name('api.services.terminate');
            Route::post('/services/{service}/change-plan', [ServiceApiController::class, 'changePlan'])->middleware('idempotency')->name('api.services.change-plan');
            Route::post('/services/{service}/renewal-previews', [ServiceApiController::class, 'renewalPreview'])->name('api.services.renewal-previews');
            Route::post('/services/{service}/renewals', [ServiceApiController::class, 'renewal'])->middleware('idempotency')->name('api.services.renewals');
            Route::post('/services/{service}/disconnect-session', [ServiceApiController::class, 'disconnectSession'])->middleware('idempotency')->name('api.services.disconnect-session');
            Route::post('/services/{service}/resync', [ServiceApiController::class, 'resync'])->middleware('idempotency')->name('api.services.resync');
            Route::post('/plans', [PlanApiController::class, 'store'])->name('api.plans.store');
            Route::post('/imports/customers', [CustomerImportController::class, 'store'])->name('api.imports.customers.store');
            Route::post('/imports/plans', [PlanImportController::class, 'store'])->name('api.imports.plans.store');
            Route::post('/imports/plans/{import}/rollback', [PlanImportController::class, 'rollback'])->name('api.imports.plans.rollback');
            Route::post('/imports/services', [ServiceImportController::class, 'store'])->name('api.imports.services.store');
            Route::post('/imports/services/{import}/rollback', [ServiceImportController::class, 'rollback'])->name('api.imports.services.rollback');
            Route::post('/imports/equipment', [EquipmentImportController::class, 'store'])->name('api.imports.equipment.store');
            Route::post('/imports/equipment/{import}/rollback', [EquipmentImportController::class, 'rollback'])->name('api.imports.equipment.rollback');
            Route::post('/imports/balances', [BalanceImportController::class, 'store'])->name('api.imports.balances.store');
            Route::post('/imports/balances/{import}/rollback', [BalanceImportController::class, 'rollback'])->name('api.imports.balances.rollback');
            Route::post('/imports/routers/{router}/subscribers', [RouterSubscriberImportController::class, 'store'])->name('api.imports.routers.subscribers.store');
            Route::post('/imports/{import}/rollback', [CustomerImportController::class, 'rollback'])->name('api.imports.rollback');
            Route::get('/partners', [PartnerApiController::class, 'index'])->name('api.partners.index');
            Route::post('/partners', [PartnerApiController::class, 'store'])->name('api.partners.store');
            Route::get('/partners/{partner}', [PartnerApiController::class, 'show'])->name('api.partners.show');
            Route::get('/partners/{partner}/wallets', [PartnerApiController::class, 'wallet'])->name('api.partners.wallets');
            Route::get('/partners/{partner}/wallet-transactions', [PartnerApiController::class, 'transactions'])->name('api.partners.wallet-transactions');
            Route::get('/partners/{partner}/catalog', [PartnerApiController::class, 'catalog'])->name('api.partners.catalog');
            Route::get('/partners/{partner}/settlements', [PartnerApiController::class, 'settlements'])->name('api.partners.settlements');
            Route::post('/partners/{partner}/settlements', [PartnerApiController::class, 'createSettlement'])->name('api.partners.settlements.create');
            Route::post('/settlements/{settlement}/approve', [PartnerApiController::class, 'approveSettlement'])->name('api.settlements.approve');
            Route::post('/settlements/{settlement}/pay', [PartnerApiController::class, 'paySettlement'])->middleware('idempotency')->name('api.settlements.pay');
            Route::post('/partners/{partner}/wallet-top-ups', [PartnerApiController::class, 'topUp'])->middleware(['idempotency', 'recent-auth'])->name('api.partners.wallet-top-ups');
            Route::post('/network/commands/{command}/retry', [NetworkCommandController::class, 'retry'])->middleware('idempotency')->name('api.network.commands.retry');
            Route::post('/provisioning-commands/{command}/retries', [NetworkCommandController::class, 'retry'])->middleware('idempotency')->name('api.provisioning-commands.retries');
            Route::get('/network-commands/{command}', [NetworkCommandController::class, 'show'])->name('api.network-commands.show');
        });
        Route::middleware('abilities:staff:collector')->group(function (): void {
            Route::get('/collector/customers', [CollectorApiController::class, 'customers'])->name('api.collector.customers');
            Route::get('/collector/customers/{customer}', [CollectorApiController::class, 'customer'])->name('api.collector.customers.show');
            Route::get('/collector/shift', [CollectorApiController::class, 'shift'])->name('api.collector.shift');
            Route::post('/collector/shift/open', [CollectorApiController::class, 'openShift'])->middleware('idempotency')->name('api.collector.shift.open');
            Route::post('/collector/shift/close', [CollectorApiController::class, 'closeShift'])->middleware('idempotency')->name('api.collector.shift.close');
            Route::get('/collector/payments', [CollectorApiController::class, 'payments'])->name('api.collector.payments');
            Route::post('/collector/payments', [CollectorPaymentController::class, 'store'])->middleware('idempotency')->name('api.collector.payments.store');
            Route::post('/collector/payments/{payment}/receipt', [CollectorApiController::class, 'resendReceipt'])->middleware('idempotency')->name('api.collector.payments.receipt');
            Route::get('/collector/summary', [CollectorApiController::class, 'summary'])->name('api.collector.summary');
            Route::post('/collector/payments/batch', [CollectorPaymentController::class, 'store'])->middleware('idempotency')->name('api.collector.payments.batch');
            Route::post('/collector/payments/whish', [CollectorPaymentController::class, 'createWhish'])->middleware('idempotency')->name('api.collector.payments.whish');
            Route::get('/collector/payments/whish/{attempt}', [CollectorPaymentController::class, 'whishStatus'])->middleware('throttle:30,1')->name('api.collector.payments.whish.status');
            Route::get('/collector/sync/bootstrap', [CollectorSyncController::class, 'bootstrap'])->name('api.collector.sync.bootstrap');
            Route::get('/collector/sync/delta', [CollectorSyncController::class, 'delta'])->name('api.collector.sync.delta');
            Route::post('/collector/sync/push', [CollectorSyncController::class, 'push'])->middleware('idempotency')->name('api.collector.sync.push');
        });
        Route::middleware('abilities:staff:technician')->group(function (): void {
            Route::post('/technician/uploads', [TechnicianMediaController::class, 'store'])->name('api.technician.uploads.store');
            Route::get('/technician/services/{service}/diagnostics', [TechnicianWorkOrderController::class, 'diagnostics'])->name('api.technician.services.diagnostics');
            Route::get('/technician/inventory', [TechnicianWorkOrderController::class, 'inventory'])->name('api.technician.inventory');
            Route::get('/technician/work-orders', [TechnicianWorkOrderController::class, 'index'])->name('api.technician.work-orders.index');
            Route::get('/technician/work-orders/{workOrder}', [TechnicianWorkOrderController::class, 'show'])->name('api.technician.work-orders.show');
            Route::post('/technician/work-orders/{workOrder}/media', [TechnicianMediaController::class, 'storeForWorkOrder'])->name('api.technician.work-orders.media.store');
            Route::post('/technician/work-orders/{workOrder}/signature', [TechnicianMediaController::class, 'storeSignature'])->name('api.technician.work-orders.signature.store');
            Route::post('/technician/work-orders/{workOrder}/readings', [TechnicianWorkOrderController::class, 'readings'])->name('api.technician.work-orders.readings.store');
            Route::post('/technician/work-orders/{workOrder}/materials', [TechnicianWorkOrderController::class, 'materials'])->name('api.technician.work-orders.materials.store');
            Route::post('/technician/work-orders/{workOrder}/status', [TechnicianWorkOrderController::class, 'status'])->name('api.technician.work-orders.status');
            Route::post('/technician/work-orders/{workOrder}/complete', [TechnicianWorkOrderController::class, 'complete'])->middleware('idempotency')->name('api.technician.work-orders.complete');
            Route::post('/technician/work-orders/{workOrder}/fail', [TechnicianWorkOrderController::class, 'fail'])->name('api.technician.work-orders.fail');
        });
    });
});
