<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\Auth\ReauthenticateController;
use App\Http\Controllers\Auth\TwoFactorController;
use App\Http\Controllers\Web\BillingController;
use App\Http\Controllers\Web\CashShiftOperationsController;
use App\Http\Controllers\Web\CredentialOperationsController;
use App\Http\Controllers\Web\CustomerController;
use App\Http\Controllers\Web\DashboardController;
use App\Http\Controllers\Web\ExchangeRateOperationsController;
use App\Http\Controllers\Web\FieldController;
use App\Http\Controllers\Web\ImportOperationsController;
use App\Http\Controllers\Web\IncidentOperationsController;
use App\Http\Controllers\Web\InventoryOperationsController;
use App\Http\Controllers\Web\InvitationController;
use App\Http\Controllers\Web\IpPoolOperationsController;
use App\Http\Controllers\Web\MediaDownloadController;
use App\Http\Controllers\Web\NetworkOperationsController;
use App\Http\Controllers\Web\NotificationController;
use App\Http\Controllers\Web\PartnerController;
use App\Http\Controllers\Web\PlanOperationsController;
use App\Http\Controllers\Web\PopOperationsController;
use App\Http\Controllers\Web\PortalPageController;
use App\Http\Controllers\Web\ProfileController;
use App\Http\Controllers\Web\ReportController;
use App\Http\Controllers\Web\RouterOperationsController;
use App\Http\Controllers\Web\SecurityController;
use App\Http\Controllers\Web\ServiceController;
use App\Http\Controllers\Web\SessionOperationsController;
use App\Http\Controllers\Web\SettingsController;
use App\Http\Controllers\Web\SupplierOperationsController;
use App\Http\Controllers\Web\TenantLogoController;
use App\Http\Controllers\Web\TicketCannedResponseController;
use App\Http\Controllers\Web\TicketOperationsController;
use App\Http\Controllers\Web\UserOperationsController;
use App\Http\Controllers\Web\WorkOrderOperationsController;
use App\Http\Controllers\Web\WorkspaceSearchController;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect()->route(auth()->check() ? 'dashboard' : 'login'));

Route::get('/docs/api', function () {
    return response()->file(base_path('openapi/isp-platform-v1.yaml'), [
        'Content-Type' => 'application/yaml; charset=UTF-8',
        'Content-Disposition' => 'inline; filename="isp-platform-v1.yaml"',
    ]);
})->name('docs.api');

Route::prefix('portal/{tenant:slug}')->group(function (): void {
    Route::get('/', [PortalPageController::class, 'signIn'])->name('portal.sign-in');
    Route::get('/dashboard', [PortalPageController::class, 'dashboard'])->name('portal.dashboard');
});

Route::get('/tenant/{tenant:slug}/logo', TenantLogoController::class)->name('tenant.logo');

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/login', [LoginController::class, 'store'])->middleware('throttle:login')->name('login.store');
    Route::get('/forgot-password', [PasswordResetController::class, 'requestForm'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'send'])->middleware('throttle:password-reset')->name('password.email');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'resetForm'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'reset'])->name('password.update');
    Route::get('/invite/{token}', [InvitationController::class, 'show'])->name('invitations.show');
    Route::post('/invite/{token}', [InvitationController::class, 'accept'])->name('invitations.accept');
});

Route::middleware(['auth', 'tenant'])->group(function (): void {
    Route::post('/logout', LogoutController::class)->name('logout');
    Route::get('/two-factor/setup', [TwoFactorController::class, 'setup'])->name('two-factor.setup');
    Route::post('/two-factor/setup', [TwoFactorController::class, 'confirm'])->middleware('recent-auth')->name('two-factor.setup.confirm');
    Route::get('/two-factor/challenge', [TwoFactorController::class, 'challenge'])->name('two-factor.challenge');
    Route::post('/two-factor/challenge', [TwoFactorController::class, 'verify'])->name('two-factor.challenge.verify');
    Route::get('/security/reauthenticate', [ReauthenticateController::class, 'create'])->name('security.reauthenticate');
    Route::post('/security/reauthenticate', [ReauthenticateController::class, 'store'])->name('security.reauthenticate.store');
    Route::get('/security/sessions', [SecurityController::class, 'sessions'])->middleware('2fa')->name('security.sessions');
    Route::delete('/security/sessions/{session}', [SecurityController::class, 'revoke'])->middleware('2fa')->name('security.sessions.revoke');
    Route::post('/settings/locale', [SecurityController::class, 'locale'])->middleware('2fa')->name('settings.locale');
});

Route::middleware(['auth', 'tenant', '2fa'])->group(function (): void {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/field', [FieldController::class, 'index'])->name('field.index');
    Route::get('/field/sync', [FieldController::class, 'sync'])->name('field.sync');
    Route::post('/field/push', [FieldController::class, 'push'])->name('field.push');
    Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications');
    Route::get('/search', WorkspaceSearchController::class)->name('workspace.search');
    Route::get('/settings/general', [SettingsController::class, 'general'])->name('settings.general');
    Route::get('/settings/readiness', [SettingsController::class, 'readiness'])->name('settings.readiness');
    Route::get('/settings/whatsapp', [SettingsController::class, 'whatsapp'])->name('settings.whatsapp');
    Route::get('/settings/ticket-responses', [TicketCannedResponseController::class, 'index'])->name('settings.ticket-responses');
    Route::post('/settings/ticket-responses', [TicketCannedResponseController::class, 'store'])->middleware('recent-auth')->name('settings.ticket-responses.store');
    Route::patch('/settings/ticket-responses/{ticketCannedResponse:public_id}', [TicketCannedResponseController::class, 'update'])->middleware('recent-auth')->name('settings.ticket-responses.update');
    Route::delete('/settings/ticket-responses/{ticketCannedResponse:public_id}', [TicketCannedResponseController::class, 'archive'])->middleware('recent-auth')->name('settings.ticket-responses.archive');
    Route::post('/settings/whatsapp/test', [SettingsController::class, 'sendWhatsAppTest'])->middleware(['recent-auth', 'throttle:3,10'])->name('settings.whatsapp.test');
    Route::post('/settings/whatsapp/accounts', [SettingsController::class, 'createWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.store');
    Route::patch('/settings/whatsapp/accounts/{whatsappAccount:public_id}', [SettingsController::class, 'updateWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.update');
    Route::post('/settings/whatsapp/accounts/{whatsappAccount:public_id}/disconnect', [SettingsController::class, 'disconnectWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.disconnect');
    Route::delete('/settings/whatsapp/accounts/{whatsappAccount:public_id}', [SettingsController::class, 'deleteWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.delete');
    Route::put('/settings/general', [SettingsController::class, 'updateGeneral'])->middleware('recent-auth')->name('settings.general.update');
    Route::get('/settings/users', [UserOperationsController::class, 'index'])->name('settings.users');
    Route::post('/settings/users/invite', [UserOperationsController::class, 'invite'])->middleware('recent-auth')->name('settings.users.invite');
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('/customers/export', [CustomerController::class, 'export'])->name('customers.export');
    Route::post('/customers/saved-views', [CustomerController::class, 'storeSavedView'])->name('customers.saved-views.store');
    Route::delete('/customers/saved-views/{savedView}', [CustomerController::class, 'destroySavedView'])->middleware('recent-auth')->name('customers.saved-views.destroy');
    Route::get('/customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('/customers', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/customers/{customer:public_id}/edit', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::put('/customers/{customer:public_id}', [CustomerController::class, 'update'])->name('customers.update');
    Route::post('/customers/{customer:public_id}/documents', [CustomerController::class, 'storeDocument'])->middleware('recent-auth')->name('customers.documents.store');
    Route::get('/customers/{customer:public_id}/payments/create', [CustomerController::class, 'createPayment'])->name('customers.payments.create');
    Route::post('/customers/{customer:public_id}/payments', [CustomerController::class, 'storePayment'])->name('customers.payments.store');
    Route::post('/customers/{customer:public_id}/payments/whish', [CustomerController::class, 'storeWhishPayment'])->name('customers.payments.whish.store');
    Route::get('/customers/{customer:public_id}/payments/whish/{attempt}', [CustomerController::class, 'whishStatus'])->middleware('throttle:30,1')->name('customers.payments.whish.status');
    Route::get('/customers/{customer:public_id}/renew', [CustomerController::class, 'renew'])->name('customers.renew');
    Route::post('/customers/{customer:public_id}/renew', [CustomerController::class, 'storeRenewal'])->name('customers.renew.store');
    Route::get('/customers/{customer:public_id}/tickets/create', [TicketOperationsController::class, 'create'])->name('operations.tickets.create');
    Route::post('/customers/{customer:public_id}/tickets', [TicketOperationsController::class, 'store'])->name('operations.tickets.store');
    Route::get('/customers/{customer:public_id}', [CustomerController::class, 'show'])->name('customers.show');
    Route::post('/customers/{customer:public_id}/anonymize', [CustomerController::class, 'anonymize'])->middleware('recent-auth')->name('customers.anonymize');
    Route::get('/services', [ServiceController::class, 'index'])->name('services.index');
    Route::get('/services/{service:public_id}', [ServiceController::class, 'show'])->name('services.show');
    Route::post('/services/{service:public_id}/activate', [ServiceController::class, 'activate'])->name('services.activate');
    Route::post('/services/{service:public_id}/suspend', [ServiceController::class, 'suspend'])->name('services.suspend');
    Route::post('/services/{service:public_id}/pause', [ServiceController::class, 'pause'])->name('services.pause');
    Route::post('/services/{service:public_id}/resume', [ServiceController::class, 'resume'])->name('services.resume');
    Route::post('/services/{service:public_id}/terminate', [ServiceController::class, 'terminate'])->name('services.terminate');
    Route::post('/services/{service:public_id}/disconnect-session', [ServiceController::class, 'disconnectSession'])->name('services.disconnect-session');
    Route::post('/services/{service:public_id}/equipment/{unit}/return', [ServiceController::class, 'returnEquipment'])->middleware('recent-auth')->name('services.equipment.return');
    Route::post('/services/{service:public_id}/resync', [ServiceController::class, 'resync'])->name('services.resync');
    Route::post('/services/{service:public_id}/change-plan', [ServiceController::class, 'changePlan'])->name('services.change-plan');
    Route::get('/operations/network-commands', [NetworkOperationsController::class, 'index'])->name('operations.network-commands');
    Route::post('/operations/network-commands/{command:public_id}/retry', [NetworkOperationsController::class, 'retry'])->name('operations.network-commands.retry');
    Route::get('/operations/sessions', [SessionOperationsController::class, 'index'])->name('operations.sessions');
    Route::get('/operations/incidents', [IncidentOperationsController::class, 'index'])->name('operations.incidents');
    Route::get('/operations/incidents/{incident:public_id}', [IncidentOperationsController::class, 'show'])->name('operations.incidents.show');
    Route::get('/operations/routers', [RouterOperationsController::class, 'index'])->name('operations.routers');
    Route::get('/operations/routers/create', [RouterOperationsController::class, 'create'])->name('operations.routers.create');
    Route::post('/operations/routers', [RouterOperationsController::class, 'store'])->middleware('recent-auth')->name('operations.routers.store');
    Route::get('/operations/routers/{router:public_id}', [RouterOperationsController::class, 'show'])->name('operations.routers.show');
    Route::put('/operations/routers/{router:public_id}', [RouterOperationsController::class, 'update'])->middleware('recent-auth')->name('operations.routers.update');
    Route::post('/operations/routers/{router:public_id}/health', [RouterOperationsController::class, 'health'])->name('operations.routers.health');
    Route::get('/operations/pops', [PopOperationsController::class, 'index'])->name('operations.pops');
    Route::post('/operations/pops', [PopOperationsController::class, 'store'])->middleware('recent-auth')->name('operations.pops.store');
    Route::get('/operations/pops/{pop}', [PopOperationsController::class, 'show'])->name('operations.pops.show');
    Route::put('/operations/pops/{pop}', [PopOperationsController::class, 'update'])->middleware('recent-auth')->name('operations.pops.update');
    Route::post('/operations/pops/{pop}/upstream-links', [PopOperationsController::class, 'storeUpstreamLink'])->middleware('recent-auth')->name('operations.pops.upstream-links.store');
    Route::get('/operations/ip-pools', [IpPoolOperationsController::class, 'index'])->name('operations.ip-pools');
    Route::post('/operations/ip-pools', [IpPoolOperationsController::class, 'storePool'])->middleware('recent-auth')->name('operations.ip-pools.store');
    Route::post('/operations/ip-pools/{pool}/addresses', [IpPoolOperationsController::class, 'storeAddress'])->middleware('recent-auth')->name('operations.ip-pools.addresses.store');
    Route::get('/billing/invoices', [BillingController::class, 'invoices'])->name('billing.invoices');
    Route::get('/billing/invoices/{invoice:public_id}', [BillingController::class, 'showInvoice'])->name('billing.invoices.show');
    Route::get('/billing/invoices/{invoice:public_id}/pdf', [BillingController::class, 'invoicePdf'])->name('billing.invoices.pdf');
    Route::post('/billing/invoices/{invoice:public_id}/issue', [BillingController::class, 'issue'])->name('billing.invoices.issue');
    Route::post('/billing/invoices/{invoice:public_id}/credit-notes', [BillingController::class, 'creditNote'])->middleware('recent-auth')->name('billing.invoices.credit-notes');
    Route::get('/billing/payments', [BillingController::class, 'payments'])->name('billing.payments');
    Route::get('/billing/payments/{payment:public_id}', [BillingController::class, 'showPayment'])->name('billing.payments.show');
    Route::get('/billing/payments/{payment:public_id}/pdf', [BillingController::class, 'paymentPdf'])->name('billing.payments.pdf');
    Route::get('/billing/shifts', [CashShiftOperationsController::class, 'index'])->name('billing.shifts');
    Route::post('/billing/shifts/open', [CashShiftOperationsController::class, 'open'])->name('billing.shifts.open');
    Route::post('/billing/shifts/{shift:public_id}/close', [CashShiftOperationsController::class, 'close'])->middleware('recent-auth')->name('billing.shifts.close');
    Route::get('/billing/exchange-rates', [ExchangeRateOperationsController::class, 'index'])->name('billing.exchange-rates');
    Route::post('/billing/exchange-rates', [ExchangeRateOperationsController::class, 'store'])->middleware('recent-auth')->name('billing.exchange-rates.store');
    Route::post('/billing/exchange-rates/sync', [ExchangeRateOperationsController::class, 'sync'])->middleware('recent-auth')->name('billing.exchange-rates.sync');
    Route::post('/billing/payments/{payment:public_id}/reverse', [BillingController::class, 'reversePayment'])->middleware('recent-auth')->name('billing.payments.reverse');
    Route::get('/operations/tickets', [TicketOperationsController::class, 'index'])->name('operations.tickets');
    Route::get('/operations/tickets/{ticket:public_id}', [TicketOperationsController::class, 'show'])->name('operations.tickets.show');
    Route::post('/operations/tickets/{ticket:public_id}/status', [TicketOperationsController::class, 'status'])->name('operations.tickets.status');
    Route::post('/operations/tickets/{ticket:public_id}/messages', [TicketOperationsController::class, 'reply'])->name('operations.tickets.messages');
    Route::post('/operations/tickets/{ticket:public_id}/assignee', [TicketOperationsController::class, 'assign'])->name('operations.tickets.assignee');
    Route::get('/operations/work-orders', [WorkOrderOperationsController::class, 'index'])->name('operations.work-orders');
    Route::get('/operations/work-orders/calendar', [WorkOrderOperationsController::class, 'calendar'])->name('operations.work-orders.calendar');
    Route::get('/operations/work-orders/{workOrder:public_id}', [WorkOrderOperationsController::class, 'show'])->name('operations.work-orders.show');
    Route::get('/operations/media/{media}/download', MediaDownloadController::class)->name('operations.media.download');
    Route::post('/operations/work-orders/{workOrder:public_id}/complete', [WorkOrderOperationsController::class, 'complete'])->name('operations.work-orders.complete');
    Route::post('/operations/work-orders/{workOrder:public_id}/schedule', [WorkOrderOperationsController::class, 'schedule'])->middleware('recent-auth')->name('operations.work-orders.schedule');
    Route::post('/operations/work-orders/{workOrder:public_id}/signature', [WorkOrderOperationsController::class, 'storeSignature'])->middleware('recent-auth')->name('operations.work-orders.signature.store');
    Route::post('/operations/work-orders/{workOrder:public_id}/readings', [WorkOrderOperationsController::class, 'readings'])->middleware('recent-auth')->name('operations.work-orders.readings.store');
    Route::post('/operations/work-orders/{workOrder:public_id}/materials', [WorkOrderOperationsController::class, 'material'])->middleware('recent-auth')->name('operations.work-orders.materials.store');
    Route::get('/operations/inventory', [InventoryOperationsController::class, 'index'])->name('operations.inventory');
    Route::post('/operations/inventory/bulk-receive', [InventoryOperationsController::class, 'receiveBulk'])->middleware('recent-auth')->name('operations.inventory.bulk-receive');
    Route::post('/operations/inventory/{unit}/assign', [InventoryOperationsController::class, 'assign'])->middleware('recent-auth')->name('operations.inventory.assign');
    Route::post('/operations/inventory/{unit}/transfer', [InventoryOperationsController::class, 'transfer'])->middleware('recent-auth')->name('operations.inventory.transfer');
    Route::get('/operations/imports', [ImportOperationsController::class, 'index'])->name('operations.imports');
    Route::post('/operations/imports', [ImportOperationsController::class, 'store'])->name('operations.imports.store');
    Route::post('/operations/imports/{import}/rollback', [ImportOperationsController::class, 'rollback'])->middleware('recent-auth')->name('operations.imports.rollback');
    Route::get('/operations/credentials', [CredentialOperationsController::class, 'index'])->name('operations.credentials');
    Route::post('/operations/credentials/import', [CredentialOperationsController::class, 'import'])->middleware('recent-auth')->name('operations.credentials.import');
    Route::post('/operations/credentials/{credential}/reveal', [CredentialOperationsController::class, 'reveal'])->middleware('recent-auth')->name('operations.credentials.reveal');
    Route::post('/operations/credentials/{credential}/assign', [CredentialOperationsController::class, 'assign'])->middleware('recent-auth')->name('operations.credentials.assign');
    Route::get('/operations/suppliers', [SupplierOperationsController::class, 'index'])->name('operations.suppliers');
    Route::post('/operations/suppliers', [SupplierOperationsController::class, 'store'])->middleware('recent-auth')->name('operations.suppliers.store');
    Route::post('/operations/suppliers/{supplier}/contracts', [SupplierOperationsController::class, 'storeContract'])->middleware('recent-auth')->name('operations.suppliers.contracts.store');
    Route::post('/operations/suppliers/{supplier}/bills', [SupplierOperationsController::class, 'storeBill'])->middleware('recent-auth')->name('operations.suppliers.bills.store');
    Route::post('/operations/supplier-bills/{bill}/payments', [SupplierOperationsController::class, 'storePayment'])->middleware('recent-auth')->name('operations.supplier-bills.payments.store');
    Route::get('/plans', [PlanOperationsController::class, 'index'])->name('plans.index');
    Route::get('/plans/create', [PlanOperationsController::class, 'create'])->name('plans.create');
    Route::post('/plans', [PlanOperationsController::class, 'store'])->name('plans.store');
    Route::post('/plans/addons', [PlanOperationsController::class, 'storeAddon'])->middleware('recent-auth')->name('plans.addons.store');
    Route::put('/plans/addons/{addon:public_id}', [PlanOperationsController::class, 'updateAddon'])->middleware('recent-auth')->name('plans.addons.update');
    Route::delete('/plans/addons/{addon:public_id}', [PlanOperationsController::class, 'archiveAddon'])->middleware('recent-auth')->name('plans.addons.archive');
    Route::post('/plans/promotions', [PlanOperationsController::class, 'storePromotion'])->middleware('recent-auth')->name('plans.promotions.store');
    Route::put('/plans/promotions/{promotion:public_id}', [PlanOperationsController::class, 'updatePromotion'])->middleware('recent-auth')->name('plans.promotions.update');
    Route::delete('/plans/promotions/{promotion:public_id}', [PlanOperationsController::class, 'archivePromotion'])->middleware('recent-auth')->name('plans.promotions.archive');
    Route::get('/customers/{customer:public_id}/services/create', [ServiceController::class, 'create'])->name('services.create');
    Route::post('/customers/{customer:public_id}/services', [ServiceController::class, 'store'])->name('services.store');
    Route::get('/partners/commercial', [PartnerController::class, 'commercial'])->name('partners.commercial');
    Route::post('/partners', [PartnerController::class, 'store'])->middleware('recent-auth')->name('partners.store');
    Route::get('/reports/finance', [ReportController::class, 'finance'])->name('reports.finance');
    Route::get('/reports/supplier-payables', [ReportController::class, 'supplierPayables'])->name('reports.supplier-payables');
    Route::get('/reports/operations', [ReportController::class, 'operations'])->name('reports.operations');
});
