<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\Auth\ReauthenticateController;
use App\Http\Controllers\Auth\TwoFactorController;
use App\Http\Controllers\Web\BillingController;
use App\Http\Controllers\Web\CashShiftOperationsController;
use App\Http\Controllers\Web\CollectorCustodyController;
use App\Http\Controllers\Web\CollectorFieldDayController;
use App\Http\Controllers\Web\CollectorRouteController;
use App\Http\Controllers\Web\CollectorTaskController;
use App\Http\Controllers\Web\CollectorTerritoryController;
use App\Http\Controllers\Web\CredentialOperationsController;
use App\Http\Controllers\Web\CustomerController;
use App\Http\Controllers\Web\DashboardController;
use App\Http\Controllers\Web\ExchangeRateOperationsController;
use App\Http\Controllers\Web\FieldController;
use App\Http\Controllers\Web\FieldInventorySaleController;
use App\Http\Controllers\Web\ImportOperationsController;
use App\Http\Controllers\Web\IncidentOperationsController;
use App\Http\Controllers\Web\InventoryOperationsController;
use App\Http\Controllers\Web\InventoryStockCountController;
use App\Http\Controllers\Web\InventoryTransferRequestController;
use App\Http\Controllers\Web\InvitationController;
use App\Http\Controllers\Web\IpPoolOperationsController;
use App\Http\Controllers\Web\LocationOperationsController;
use App\Http\Controllers\Web\MediaDownloadController;
use App\Http\Controllers\Web\NetworkOperationsController;
use App\Http\Controllers\Web\NotificationController;
use App\Http\Controllers\Web\NotificationTemplateController;
use App\Http\Controllers\Web\OpticalOperationsController;
use App\Http\Controllers\Web\OperationalExpenseController;
use App\Http\Controllers\Web\PartnerController;
use App\Http\Controllers\Web\PlanOperationsController;
use App\Http\Controllers\Web\PlatformTenantController;
use App\Http\Controllers\Web\PopOperationsController;
use App\Http\Controllers\Web\PortalPageController;
use App\Http\Controllers\Web\ProfileController;
use App\Http\Controllers\Web\PublicBillingLinkController;
use App\Http\Controllers\Web\PublicBillingPageController;
use App\Http\Controllers\Web\ReportController;
use App\Http\Controllers\Web\RouterOperationsController;
use App\Http\Controllers\Web\SecurityController;
use App\Http\Controllers\Web\ServiceController;
use App\Http\Controllers\Web\SessionOperationsController;
use App\Http\Controllers\Web\SettingsController;
use App\Http\Controllers\Web\SupplierOperationsController;
use App\Http\Controllers\Web\TenantLogoController;
use App\Http\Controllers\Web\TicketCannedResponseController;
use App\Http\Controllers\Web\TicketOperationsController;
use App\Http\Controllers\Web\TopologyOperationsController;
use App\Http\Controllers\Web\UserOperationsController;
use App\Http\Controllers\Web\WorkOrderOperationsController;
use App\Http\Controllers\Web\WorkspaceSearchController;
use App\Models\User;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    $user = auth()->user();

    if (! $user instanceof User) {
        return redirect()->route('login');
    }

    return redirect()->route($user->isPlatformOperator() ? 'admin.tenants' : 'dashboard');
});

Route::get('/docs/api', function () {
    return response()->file(base_path('openapi/isp-platform-v1.yaml'), [
        'Content-Type' => 'application/yaml; charset=UTF-8',
        'Content-Disposition' => 'inline; filename="isp-platform-v1.yaml"',
    ]);
})->name('docs.api');

Route::prefix('portal/{tenant:slug}')->group(function (): void {
    Route::get('/', [PortalPageController::class, 'signIn'])->name('portal.sign-in');
    Route::get('/dashboard', [PortalPageController::class, 'dashboard'])->name('portal.dashboard');
});

Route::get('/tenant/{tenant:slug}/logo', TenantLogoController::class)->name('tenant.logo');
Route::get('/share/{token}', [PublicBillingPageController::class, 'show'])->middleware('throttle:60,1')->name('public.billing.show');
Route::get('/share/{token}/pdf', [PublicBillingPageController::class, 'pdf'])->middleware('throttle:60,1')->name('public.billing.pdf');

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/login', [LoginController::class, 'store'])->middleware('throttle:login')->name('login.store');
    Route::get('/forgot-password', [PasswordResetController::class, 'requestForm'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'send'])->middleware('throttle:password-reset')->name('password.email');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'resetForm'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'reset'])->name('password.update');
    Route::get('/invite/{token}', [InvitationController::class, 'show'])->name('invitations.show');
    Route::post('/invite/{token}', [InvitationController::class, 'accept'])->name('invitations.accept');
});

Route::middleware(['auth'])->group(function (): void {
    Route::post('/logout', LogoutController::class)->name('logout');
    Route::get('/two-factor/setup', [TwoFactorController::class, 'setup'])->name('two-factor.setup');
    Route::post('/two-factor/setup', [TwoFactorController::class, 'confirm'])->middleware('recent-auth')->name('two-factor.setup.confirm');
    Route::get('/two-factor/challenge', [TwoFactorController::class, 'challenge'])->name('two-factor.challenge');
    Route::post('/two-factor/challenge', [TwoFactorController::class, 'verify'])->name('two-factor.challenge.verify');
    Route::get('/security/reauthenticate', [ReauthenticateController::class, 'create'])->name('security.reauthenticate');
    Route::post('/security/reauthenticate', [ReauthenticateController::class, 'store'])->name('security.reauthenticate.store');
});

Route::middleware(['auth', 'tenant'])->group(function (): void {
    Route::get('/security/sessions', [SecurityController::class, 'sessions'])->middleware('2fa')->name('security.sessions');
    Route::delete('/security/sessions/{session}', [SecurityController::class, 'revoke'])->middleware('2fa')->name('security.sessions.revoke');
    Route::post('/settings/locale', [SecurityController::class, 'locale'])->middleware('2fa')->name('settings.locale');
});

Route::middleware(['auth', 'platform', '2fa'])->prefix('admin')->group(function (): void {
    Route::get('/tenants', [PlatformTenantController::class, 'index'])->name('admin.tenants');
    Route::post('/tenants', [PlatformTenantController::class, 'store'])->middleware('recent-auth')->name('admin.tenants.store');
    Route::patch('/tenants/{tenant:public_id}', [PlatformTenantController::class, 'update'])->middleware('recent-auth')->name('admin.tenants.update');
});

Route::middleware(['auth', 'tenant', '2fa'])->group(function (): void {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/field', [FieldController::class, 'index'])->name('field.index');
    Route::get('/field/sync', [FieldController::class, 'sync'])->name('field.sync');
    Route::post('/field/push', [FieldController::class, 'push'])->name('field.push');
    Route::post('/field/check-in', [CollectorFieldDayController::class, 'checkIn'])->name('field.check-in');
    Route::post('/field/check-out', [CollectorFieldDayController::class, 'checkOut'])->name('field.check-out');
    Route::post('/field/route-stops/{routeStop:public_id}', [CollectorRouteController::class, 'recordStop'])->name('field.route-stops.record');
    Route::post('/field/tasks/{collectorTask:public_id}/messages', [CollectorTaskController::class, 'message'])->name('field.tasks.messages.store');
    Route::patch('/field/tasks/{collectorTask:public_id}/status', [CollectorTaskController::class, 'status'])->name('field.tasks.status');
    Route::post('/field/tasks/{collectorTask:public_id}/read', [CollectorTaskController::class, 'read'])->name('field.tasks.read');
    Route::post('/field/custody', [CollectorCustodyController::class, 'storeField'])->name('field.custody.store');
    Route::post('/field/inventory-requests', [InventoryTransferRequestController::class, 'store'])->name('field.inventory-requests.store');
    Route::post('/field/stock-counts', [InventoryStockCountController::class, 'store'])->name('field.stock-counts.store');
    Route::post('/field/inventory-sales', [FieldInventorySaleController::class, 'store'])->name('field.inventory-sales.store');
    Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications');
    Route::get('/search', WorkspaceSearchController::class)->name('workspace.search');
    Route::get('/settings', fn () => redirect()->route('settings.general'))->name('settings');
    Route::get('/settings/general', [SettingsController::class, 'general'])->name('settings.general');
    Route::get('/settings/setup', [SettingsController::class, 'setup'])->name('settings.setup');
    Route::get('/settings/integrations', [SettingsController::class, 'integrations'])->name('settings.integrations');
    Route::put('/settings/integrations', [SettingsController::class, 'updateIntegrations'])->middleware('recent-auth')->name('settings.integrations.update');
    Route::get('/settings/readiness', [SettingsController::class, 'readiness'])->name('settings.readiness');
    Route::post('/settings/readiness/provider-check', [SettingsController::class, 'providerCheck'])->middleware('recent-auth')->name('settings.readiness.provider-check');
    Route::post('/settings/readiness/backup', [SettingsController::class, 'runBackup'])->middleware('recent-auth')->name('settings.readiness.backup');
    Route::get('/settings/locations', [LocationOperationsController::class, 'index'])->name('settings.locations');
    Route::post('/settings/locations/branches', [LocationOperationsController::class, 'storeBranch'])->middleware('recent-auth')->name('settings.locations.branches.store');
    Route::patch('/settings/locations/branches/{branch}', [LocationOperationsController::class, 'updateBranch'])->middleware('recent-auth')->name('settings.locations.branches.update');
    Route::post('/settings/locations/zones', [LocationOperationsController::class, 'storeZone'])->middleware('recent-auth')->name('settings.locations.zones.store');
    Route::patch('/settings/locations/zones/{zone}', [LocationOperationsController::class, 'updateZone'])->middleware('recent-auth')->name('settings.locations.zones.update');
    Route::get('/settings/whatsapp', [SettingsController::class, 'whatsapp'])->name('settings.whatsapp');
    Route::get('/settings/ticket-responses', [TicketCannedResponseController::class, 'index'])->name('settings.ticket-responses');
    Route::get('/settings/notification-templates', [NotificationTemplateController::class, 'index'])->name('settings.notification-templates');
    Route::patch('/settings/notification-templates/{messageTemplate}', [NotificationTemplateController::class, 'update'])->middleware('recent-auth')->name('settings.notification-templates.update');
    Route::post('/settings/ticket-responses', [TicketCannedResponseController::class, 'store'])->middleware('recent-auth')->name('settings.ticket-responses.store');
    Route::patch('/settings/ticket-responses/{ticketCannedResponse:public_id}', [TicketCannedResponseController::class, 'update'])->middleware('recent-auth')->name('settings.ticket-responses.update');
    Route::delete('/settings/ticket-responses/{ticketCannedResponse:public_id}', [TicketCannedResponseController::class, 'archive'])->middleware('recent-auth')->name('settings.ticket-responses.archive');
    Route::post('/settings/whatsapp/test', [SettingsController::class, 'sendWhatsAppTest'])->middleware(['recent-auth', 'throttle:3,10'])->name('settings.whatsapp.test');
    Route::post('/settings/whatsapp/accounts', [SettingsController::class, 'createWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.store');
    Route::patch('/settings/whatsapp/accounts/{whatsappAccount:public_id}', [SettingsController::class, 'updateWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.update');
    Route::post('/settings/whatsapp/accounts/{whatsappAccount:public_id}/disconnect', [SettingsController::class, 'disconnectWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.disconnect');
    Route::delete('/settings/whatsapp/accounts/{whatsappAccount:public_id}', [SettingsController::class, 'deleteWhatsAppAccount'])->middleware('recent-auth')->name('settings.whatsapp.accounts.delete');
    Route::put('/settings/general', [SettingsController::class, 'updateGeneral'])->middleware('recent-auth')->name('settings.general.update');
    Route::get('/settings/users', [UserOperationsController::class, 'index'])->name('settings.users');
    Route::post('/settings/users/invite', [UserOperationsController::class, 'invite'])->middleware('recent-auth')->name('settings.users.invite');
    Route::patch('/settings/users/{user}', [UserOperationsController::class, 'updateRole'])->middleware('recent-auth')->name('settings.users.role');
    Route::get('/settings/collector-territories', [CollectorTerritoryController::class, 'index'])->name('settings.collector-territories');
    Route::patch('/settings/collector-territories/{collector}', [CollectorTerritoryController::class, 'update'])->middleware('recent-auth')->name('settings.collector-territories.update');
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('/customers/export', [CustomerController::class, 'export'])->name('customers.export');
    Route::post('/customers/saved-views', [CustomerController::class, 'storeSavedView'])->name('customers.saved-views.store');
    Route::delete('/customers/saved-views/{savedView}', [CustomerController::class, 'destroySavedView'])->middleware('recent-auth')->name('customers.saved-views.destroy');
    Route::get('/customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('/customers', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/customers/{customer:public_id}/edit', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::put('/customers/{customer:public_id}', [CustomerController::class, 'update'])->name('customers.update');
    Route::post('/customers/{customer:public_id}/documents', [CustomerController::class, 'storeDocument'])->middleware('recent-auth')->name('customers.documents.store');
    Route::get('/customers/{customer:public_id}/payments/create', [CustomerController::class, 'createPayment'])->name('customers.payments.create');
    Route::post('/customers/{customer:public_id}/payments', [CustomerController::class, 'storePayment'])->name('customers.payments.store');
    Route::post('/customers/{customer:public_id}/payments/whish', [CustomerController::class, 'storeWhishPayment'])->name('customers.payments.whish.store');
    Route::get('/customers/{customer:public_id}/payments/whish/{attempt}', [CustomerController::class, 'whishStatus'])->middleware('throttle:30,1')->name('customers.payments.whish.status');
    Route::get('/customers/{customer:public_id}/renew', [CustomerController::class, 'renew'])->name('customers.renew');
    Route::post('/customers/{customer:public_id}/renew', [CustomerController::class, 'storeRenewal'])->name('customers.renew.store');
    Route::get('/customers/{customer:public_id}/tickets/create', [TicketOperationsController::class, 'create'])->name('operations.tickets.create');
    Route::post('/customers/{customer:public_id}/tickets', [TicketOperationsController::class, 'store'])->name('operations.tickets.store');
    Route::get('/customers/{customer:public_id}', [CustomerController::class, 'show'])->name('customers.show');
    Route::post('/customers/{customer:public_id}/anonymize', [CustomerController::class, 'anonymize'])->middleware('recent-auth')->name('customers.anonymize');
    Route::get('/services', [ServiceController::class, 'index'])->name('services.index');
    Route::get('/services/{service:public_id}', [ServiceController::class, 'show'])->name('services.show');
    Route::post('/services/{service:public_id}/activate', [ServiceController::class, 'activate'])->name('services.activate');
    Route::post('/services/{service:public_id}/suspend', [ServiceController::class, 'suspend'])->name('services.suspend');
    Route::post('/services/{service:public_id}/pause', [ServiceController::class, 'pause'])->name('services.pause');
    Route::post('/services/{service:public_id}/resume', [ServiceController::class, 'resume'])->name('services.resume');
    Route::post('/services/{service:public_id}/terminate', [ServiceController::class, 'terminate'])->name('services.terminate');
    Route::post('/services/{service:public_id}/disconnect-session', [ServiceController::class, 'disconnectSession'])->name('services.disconnect-session');
    Route::post('/services/{service:public_id}/equipment/{unit}/return', [ServiceController::class, 'returnEquipment'])->middleware('recent-auth')->name('services.equipment.return');
    Route::post('/services/{service:public_id}/resync', [ServiceController::class, 'resync'])->name('services.resync');
    Route::post('/services/{service:public_id}/addons', [ServiceController::class, 'attachAddon'])->middleware('recent-auth')->name('services.addons.attach');
    Route::delete('/services/{service:public_id}/addons/{serviceAddon:public_id}', [ServiceController::class, 'cancelAddon'])->middleware('recent-auth')->name('services.addons.cancel');
    Route::get('/services/{service:public_id}/plan-change-preview', [ServiceController::class, 'planChangePreview'])->name('services.plan-change-preview');
    Route::post('/services/{service:public_id}/change-plan', [ServiceController::class, 'changePlan'])->name('services.change-plan');
    Route::delete('/services/{service:public_id}/change-plan', [ServiceController::class, 'cancelPlan'])->name('services.change-plan.cancel');
    Route::get('/services/{service:public_id}/billing-cycle-preview', [ServiceController::class, 'billingCyclePreview'])->name('services.billing-cycle-preview');
    Route::post('/services/{service:public_id}/billing-cycle', [ServiceController::class, 'scheduleBillingCycle'])->name('services.billing-cycle.schedule');
    Route::delete('/services/{service:public_id}/billing-cycle', [ServiceController::class, 'cancelBillingCycle'])->name('services.billing-cycle.cancel');
    Route::get('/operations/network-commands', [NetworkOperationsController::class, 'index'])->name('operations.network-commands');
    Route::get('/operations/collector-check-ins', [CollectorFieldDayController::class, 'index'])->name('operations.collector-check-ins');
    Route::get('/operations/collector-routes', [CollectorRouteController::class, 'index'])->name('operations.collector-routes');
    Route::post('/operations/collector-routes', [CollectorRouteController::class, 'store'])->middleware('recent-auth')->name('operations.collector-routes.store');
    Route::get('/operations/collector-tasks', [CollectorTaskController::class, 'index'])->name('operations.collector-tasks');
    Route::post('/operations/collector-tasks', [CollectorTaskController::class, 'store'])->name('operations.collector-tasks.store');
    Route::post('/operations/collector-tasks/{collectorTask:public_id}/messages', [CollectorTaskController::class, 'message'])->name('operations.collector-tasks.messages.store');
    Route::patch('/operations/collector-tasks/{collectorTask:public_id}/status', [CollectorTaskController::class, 'status'])->name('operations.collector-tasks.status');
    Route::post('/operations/collector-tasks/{collectorTask:public_id}/read', [CollectorTaskController::class, 'read'])->name('operations.collector-tasks.read');
    Route::get('/operations/collector-custody', [CollectorCustodyController::class, 'index'])->name('operations.collector-custody');
    Route::post('/operations/collector-custody', [CollectorCustodyController::class, 'storeManager'])->name('operations.collector-custody.store');
    Route::patch('/operations/collector-custody/{collectorCustodyEntry:public_id}/review', [CollectorCustodyController::class, 'review'])->name('operations.collector-custody.review');
    Route::get('/operations/expenses', [OperationalExpenseController::class, 'index'])->name('operations.expenses');
    Route::post('/operations/expenses', [OperationalExpenseController::class, 'store'])->name('operations.expenses.store');
    Route::patch('/operations/expenses/{operationalExpense:public_id}/review', [OperationalExpenseController::class, 'review'])->middleware('recent-auth')->name('operations.expenses.review');
    Route::post('/operations/expense-categories', [OperationalExpenseController::class, 'storeCategory'])->middleware('recent-auth')->name('operations.expense-categories.store');
    Route::patch('/operations/expense-categories/{expenseCategory:public_id}', [OperationalExpenseController::class, 'updateCategory'])->middleware('recent-auth')->name('operations.expense-categories.update');
    Route::post('/operations/expense-vendors', [OperationalExpenseController::class, 'storeVendor'])->middleware('recent-auth')->name('operations.expense-vendors.store');
    Route::patch('/operations/expense-vendors/{expenseVendor:public_id}', [OperationalExpenseController::class, 'updateVendor'])->middleware('recent-auth')->name('operations.expense-vendors.update');
    Route::post('/operations/recurring-expenses', [OperationalExpenseController::class, 'storeRecurring'])->middleware('recent-auth')->name('operations.recurring-expenses.store');
    Route::patch('/operations/recurring-expenses/{recurringExpenseSchedule:public_id}', [OperationalExpenseController::class, 'updateRecurring'])->middleware('recent-auth')->name('operations.recurring-expenses.update');
    Route::post('/operations/network-commands/{command:public_id}/retry', [NetworkOperationsController::class, 'retry'])->name('operations.network-commands.retry');
    Route::get('/operations/sessions', [SessionOperationsController::class, 'index'])->name('operations.sessions');
    Route::get('/operations/incidents', [IncidentOperationsController::class, 'index'])->name('operations.incidents');
    Route::get('/operations/incidents/{incident:public_id}', [IncidentOperationsController::class, 'show'])->name('operations.incidents.show');
    Route::get('/operations/routers', [RouterOperationsController::class, 'index'])->name('operations.routers');
    Route::get('/operations/routers/create', [RouterOperationsController::class, 'create'])->name('operations.routers.create');
    Route::post('/operations/routers', [RouterOperationsController::class, 'store'])->middleware('recent-auth')->name('operations.routers.store');
    Route::get('/operations/routers/{router:public_id}', [RouterOperationsController::class, 'show'])->name('operations.routers.show');
    Route::put('/operations/routers/{router:public_id}', [RouterOperationsController::class, 'update'])->middleware('recent-auth')->name('operations.routers.update');
    Route::post('/operations/routers/{router:public_id}/health', [RouterOperationsController::class, 'health'])->name('operations.routers.health');
    Route::get('/operations/pops', [PopOperationsController::class, 'index'])->name('operations.pops');
    Route::post('/operations/pops', [PopOperationsController::class, 'store'])->middleware('recent-auth')->name('operations.pops.store');
    Route::get('/operations/pops/{pop}', [PopOperationsController::class, 'show'])->name('operations.pops.show');
    Route::get('/operations/topology/buildings', [TopologyOperationsController::class, 'index'])->name('operations.topology.buildings');
    Route::post('/operations/topology/buildings', [TopologyOperationsController::class, 'storeBuilding'])->middleware('recent-auth')->name('operations.topology.buildings.store');
    Route::get('/operations/topology/buildings/{networkBuilding:public_id}', [TopologyOperationsController::class, 'show'])->name('operations.topology.buildings.show');
    Route::put('/operations/topology/buildings/{networkBuilding:public_id}', [TopologyOperationsController::class, 'updateBuilding'])->middleware('recent-auth')->name('operations.topology.buildings.update');
    Route::post('/operations/topology/buildings/{networkBuilding:public_id}/boxes', [TopologyOperationsController::class, 'storeBox'])->middleware('recent-auth')->name('operations.topology.boxes.store');
    Route::put('/operations/topology/boxes/{distributionBox:public_id}', [TopologyOperationsController::class, 'updateBox'])->middleware('recent-auth')->name('operations.topology.boxes.update');
    Route::post('/operations/topology/services/{service:public_id}/assignment', [TopologyOperationsController::class, 'assignService'])->middleware('recent-auth')->name('operations.topology.services.assign');
    Route::delete('/operations/topology/services/{service:public_id}/assignment', [TopologyOperationsController::class, 'unassignService'])->middleware('recent-auth')->name('operations.topology.services.unassign');
    Route::get('/operations/optical', [OpticalOperationsController::class, 'index'])->name('operations.optical');
    Route::post('/operations/optical/devices', [OpticalOperationsController::class, 'storeDevice'])->middleware('recent-auth')->name('operations.optical.devices.store');
    Route::patch('/operations/optical/devices/{opticalDevice:public_id}', [OpticalOperationsController::class, 'updateDevice'])->middleware('recent-auth')->name('operations.optical.devices.update');
    Route::post('/operations/optical/readings', [OpticalOperationsController::class, 'recordReading'])->middleware('recent-auth')->name('operations.optical.readings.store');
    Route::put('/operations/pops/{pop}', [PopOperationsController::class, 'update'])->middleware('recent-auth')->name('operations.pops.update');
    Route::post('/operations/pops/{pop}/upstream-links', [PopOperationsController::class, 'storeUpstreamLink'])->middleware('recent-auth')->name('operations.pops.upstream-links.store');
    Route::patch('/operations/upstream-links/{link}', [PopOperationsController::class, 'updateUpstreamLink'])->middleware('recent-auth')->name('operations.pops.upstream-links.update');
    Route::get('/operations/ip-pools', [IpPoolOperationsController::class, 'index'])->name('operations.ip-pools');
    Route::post('/operations/ip-pools', [IpPoolOperationsController::class, 'storePool'])->middleware('recent-auth')->name('operations.ip-pools.store');
    Route::patch('/operations/ip-pools/{pool}', [IpPoolOperationsController::class, 'updatePool'])->middleware('recent-auth')->name('operations.ip-pools.update');
    Route::post('/operations/ip-pools/{pool}/addresses', [IpPoolOperationsController::class, 'storeAddress'])->middleware('recent-auth')->name('operations.ip-pools.addresses.store');
    Route::get('/billing/invoices', [BillingController::class, 'invoices'])->name('billing.invoices');
    Route::get('/billing/bulk-renewals', [BillingController::class, 'bulkRenewals'])->name('billing.bulk-renewals');
    Route::post('/billing/bulk-renewals', [BillingController::class, 'storeBulkRenewals'])->middleware('recent-auth')->name('billing.bulk-renewals.store');
    Route::get('/billing/invoices/create', [BillingController::class, 'createInvoice'])->name('billing.invoices.create');
    Route::get('/billing/invoices/customers', [BillingController::class, 'invoiceCustomers'])->name('billing.invoices.customers');
    Route::post('/billing/invoices', [BillingController::class, 'storeInvoice'])->name('billing.invoices.store');
    Route::get('/billing/credit-notes', [BillingController::class, 'creditNotes'])->name('billing.credit-notes');
    Route::get('/billing/invoices/{invoice:public_id}', [BillingController::class, 'showInvoice'])->name('billing.invoices.show');
    Route::get('/billing/invoices/{invoice:public_id}/pdf', [BillingController::class, 'invoicePdf'])->name('billing.invoices.pdf');
    Route::post('/billing/invoices/{invoice:public_id}/issue', [BillingController::class, 'issue'])->name('billing.invoices.issue');
    Route::post('/billing/invoices/{invoice:public_id}/credit-notes', [BillingController::class, 'creditNote'])->middleware('recent-auth')->name('billing.invoices.credit-notes');
    Route::get('/billing/payments', [BillingController::class, 'payments'])->name('billing.payments');
    Route::get('/billing/payments/{payment:public_id}', [BillingController::class, 'showPayment'])->name('billing.payments.show');
    Route::get('/billing/payments/{payment:public_id}/pdf', [BillingController::class, 'paymentPdf'])->name('billing.payments.pdf');
    Route::get('/billing/payments/{payment:public_id}/compact-pdf', [BillingController::class, 'compactPaymentPdf'])->name('billing.payments.compact-pdf');
    Route::post('/billing/invoices/{invoice:public_id}/public-links', [PublicBillingLinkController::class, 'invoice'])->name('billing.invoices.public-links.store');
    Route::post('/billing/payments/{payment:public_id}/public-links', [PublicBillingLinkController::class, 'receipt'])->name('billing.payments.public-links.store');
    Route::post('/customers/{customer:public_id}/statement-links', [PublicBillingLinkController::class, 'statement'])->name('customers.statement-links.store');
    Route::delete('/billing/public-links/{publicBillingLink:public_id}', [PublicBillingLinkController::class, 'destroy'])->middleware('recent-auth')->name('billing.public-links.destroy');
    Route::get('/billing/shifts', [CashShiftOperationsController::class, 'index'])->name('billing.shifts');
    Route::post('/billing/shifts/open', [CashShiftOperationsController::class, 'open'])->name('billing.shifts.open');
    Route::post('/billing/shifts/{shift:public_id}/close', [CashShiftOperationsController::class, 'close'])->middleware('recent-auth')->name('billing.shifts.close');
    Route::get('/billing/exchange-rates', [ExchangeRateOperationsController::class, 'index'])->name('billing.exchange-rates');
    Route::post('/billing/exchange-rates', [ExchangeRateOperationsController::class, 'store'])->middleware('recent-auth')->name('billing.exchange-rates.store');
    Route::post('/billing/exchange-rates/sync', [ExchangeRateOperationsController::class, 'sync'])->middleware('recent-auth')->name('billing.exchange-rates.sync');
    Route::post('/billing/payments/{payment:public_id}/reverse', [BillingController::class, 'reversePayment'])->middleware('recent-auth')->name('billing.payments.reverse');
    Route::get('/operations/tickets', [TicketOperationsController::class, 'index'])->name('operations.tickets');
    Route::get('/operations/tickets/{ticket:public_id}', [TicketOperationsController::class, 'show'])->name('operations.tickets.show');
    Route::post('/operations/tickets/{ticket:public_id}/status', [TicketOperationsController::class, 'status'])->name('operations.tickets.status');
    Route::post('/operations/tickets/{ticket:public_id}/messages', [TicketOperationsController::class, 'reply'])->name('operations.tickets.messages');
    Route::post('/operations/tickets/{ticket:public_id}/assignee', [TicketOperationsController::class, 'assign'])->name('operations.tickets.assignee');
    Route::get('/operations/work-orders', [WorkOrderOperationsController::class, 'index'])->name('operations.work-orders');
    Route::get('/operations/work-orders/calendar', [WorkOrderOperationsController::class, 'calendar'])->name('operations.work-orders.calendar');
    Route::get('/operations/work-orders/{workOrder:public_id}', [WorkOrderOperationsController::class, 'show'])->name('operations.work-orders.show');
    Route::get('/operations/media/{media}/download', MediaDownloadController::class)->name('operations.media.download');
    Route::post('/operations/work-orders/{workOrder:public_id}/complete', [WorkOrderOperationsController::class, 'complete'])->name('operations.work-orders.complete');
    Route::post('/operations/work-orders/{workOrder:public_id}/installation', [WorkOrderOperationsController::class, 'saveInstallation'])->middleware('recent-auth')->name('operations.work-orders.installation.save');
    Route::post('/operations/work-orders/{workOrder:public_id}/activation-acceptance', [WorkOrderOperationsController::class, 'acceptActivation'])->middleware('recent-auth')->name('operations.work-orders.activation.accept');
    Route::post('/operations/work-orders/{workOrder:public_id}/schedule', [WorkOrderOperationsController::class, 'schedule'])->middleware('recent-auth')->name('operations.work-orders.schedule');
    Route::post('/operations/work-orders/{workOrder:public_id}/signature', [WorkOrderOperationsController::class, 'storeSignature'])->middleware('recent-auth')->name('operations.work-orders.signature.store');
    Route::post('/operations/work-orders/{workOrder:public_id}/readings', [WorkOrderOperationsController::class, 'readings'])->middleware('recent-auth')->name('operations.work-orders.readings.store');
    Route::post('/operations/work-orders/{workOrder:public_id}/materials', [WorkOrderOperationsController::class, 'material'])->middleware('recent-auth')->name('operations.work-orders.materials.store');
    Route::get('/operations/inventory', [InventoryOperationsController::class, 'index'])->name('operations.inventory');
    Route::post('/operations/inventory/items', [InventoryOperationsController::class, 'storeItem'])->middleware('recent-auth')->name('operations.inventory.items.store');
    Route::patch('/operations/inventory/items/{item}', [InventoryOperationsController::class, 'updateItem'])->middleware('recent-auth')->name('operations.inventory.items.update');
    Route::post('/operations/inventory/warehouses', [InventoryOperationsController::class, 'storeWarehouse'])->middleware('recent-auth')->name('operations.inventory.warehouses.store');
    Route::patch('/operations/inventory/warehouses/{warehouse}', [InventoryOperationsController::class, 'updateWarehouse'])->middleware('recent-auth')->name('operations.inventory.warehouses.update');
    Route::post('/operations/inventory/serialized-receive', [InventoryOperationsController::class, 'receiveUnit'])->middleware('recent-auth')->name('operations.inventory.serialized-receive');
    Route::post('/operations/inventory/bulk-receive', [InventoryOperationsController::class, 'receiveBulk'])->middleware('recent-auth')->name('operations.inventory.bulk-receive');
    Route::post('/operations/inventory/bulk-transfer', [InventoryOperationsController::class, 'transferBulk'])->middleware('recent-auth')->name('operations.inventory.bulk-transfer');
    Route::patch('/operations/inventory/requests/{inventoryTransferRequest:public_id}', [InventoryTransferRequestController::class, 'review'])->middleware('recent-auth')->name('operations.inventory.requests.review');
    Route::patch('/operations/inventory/stock-counts/{inventoryStockCount:public_id}', [InventoryStockCountController::class, 'review'])->middleware('recent-auth')->name('operations.inventory.stock-counts.review');
    Route::post('/operations/inventory/{unit}/assign', [InventoryOperationsController::class, 'assign'])->middleware('recent-auth')->name('operations.inventory.assign');
    Route::post('/operations/inventory/{unit}/transfer', [InventoryOperationsController::class, 'transfer'])->middleware('recent-auth')->name('operations.inventory.transfer');
    Route::get('/operations/imports', [ImportOperationsController::class, 'index'])->name('operations.imports');
    Route::post('/operations/imports', [ImportOperationsController::class, 'store'])->name('operations.imports.store');
    Route::post('/operations/imports/{import}/rollback', [ImportOperationsController::class, 'rollback'])->middleware('recent-auth')->name('operations.imports.rollback');
    Route::get('/operations/credentials', [CredentialOperationsController::class, 'index'])->name('operations.credentials');
    Route::post('/operations/credentials/import', [CredentialOperationsController::class, 'import'])->middleware('recent-auth')->name('operations.credentials.import');
    Route::post('/operations/credentials/{credential}/reveal', [CredentialOperationsController::class, 'reveal'])->middleware('recent-auth')->name('operations.credentials.reveal');
    Route::post('/operations/credentials/{credential}/assign', [CredentialOperationsController::class, 'assign'])->middleware('recent-auth')->name('operations.credentials.assign');
    Route::get('/operations/suppliers', [SupplierOperationsController::class, 'index'])->name('operations.suppliers');
    Route::post('/operations/suppliers', [SupplierOperationsController::class, 'store'])->middleware('recent-auth')->name('operations.suppliers.store');
    Route::patch('/operations/suppliers/{supplier}', [SupplierOperationsController::class, 'update'])->middleware('recent-auth')->name('operations.suppliers.update');
    Route::post('/operations/suppliers/{supplier}/contracts', [SupplierOperationsController::class, 'storeContract'])->middleware('recent-auth')->name('operations.suppliers.contracts.store');
    Route::patch('/operations/supplier-contracts/{contract}', [SupplierOperationsController::class, 'updateContract'])->middleware('recent-auth')->name('operations.suppliers.contracts.update');
    Route::post('/operations/suppliers/{supplier}/bills', [SupplierOperationsController::class, 'storeBill'])->middleware('recent-auth')->name('operations.suppliers.bills.store');
    Route::post('/operations/supplier-bills/{bill}/payments', [SupplierOperationsController::class, 'storePayment'])->middleware('recent-auth')->name('operations.supplier-bills.payments.store');
    Route::get('/plans', [PlanOperationsController::class, 'index'])->name('plans.index');
    Route::get('/plans/create', [PlanOperationsController::class, 'create'])->name('plans.create');
    Route::post('/plans', [PlanOperationsController::class, 'store'])->name('plans.store');
    Route::get('/plans/{plan:public_id}/edit', [PlanOperationsController::class, 'edit'])->name('plans.edit');
    Route::put('/plans/{plan:public_id}', [PlanOperationsController::class, 'update'])->name('plans.update');
    Route::post('/plans/addons', [PlanOperationsController::class, 'storeAddon'])->middleware('recent-auth')->name('plans.addons.store');
    Route::put('/plans/addons/{addon:public_id}', [PlanOperationsController::class, 'updateAddon'])->middleware('recent-auth')->name('plans.addons.update');
    Route::delete('/plans/addons/{addon:public_id}', [PlanOperationsController::class, 'archiveAddon'])->middleware('recent-auth')->name('plans.addons.archive');
    Route::post('/plans/usage-rates', [PlanOperationsController::class, 'storeUsageRate'])->middleware('recent-auth')->name('plans.usage-rates.store');
    Route::put('/plans/usage-rates/{usageRate:public_id}', [PlanOperationsController::class, 'updateUsageRate'])->middleware('recent-auth')->name('plans.usage-rates.update');
    Route::delete('/plans/usage-rates/{usageRate:public_id}', [PlanOperationsController::class, 'archiveUsageRate'])->middleware('recent-auth')->name('plans.usage-rates.archive');
    Route::post('/plans/promotions', [PlanOperationsController::class, 'storePromotion'])->middleware('recent-auth')->name('plans.promotions.store');
    Route::put('/plans/promotions/{promotion:public_id}', [PlanOperationsController::class, 'updatePromotion'])->middleware('recent-auth')->name('plans.promotions.update');
    Route::delete('/plans/promotions/{promotion:public_id}', [PlanOperationsController::class, 'archivePromotion'])->middleware('recent-auth')->name('plans.promotions.archive');
    Route::get('/customers/{customer:public_id}/services/create', [ServiceController::class, 'create'])->name('services.create');
    Route::post('/customers/{customer:public_id}/services', [ServiceController::class, 'store'])->name('services.store');
    Route::get('/partners/commercial', [PartnerController::class, 'commercial'])->name('partners.commercial');
    Route::post('/partners', [PartnerController::class, 'store'])->middleware('recent-auth')->name('partners.store');
    Route::patch('/partners/{partner:public_id}', [PartnerController::class, 'update'])->middleware('recent-auth')->name('partners.update');
    Route::post('/partners/{partner:public_id}/price-books/items', [PartnerController::class, 'savePriceBookItem'])->middleware('recent-auth')->name('partners.price-books.items.store');
    Route::post('/partners/{partner:public_id}/wallet/fund', [PartnerController::class, 'fundWallet'])->middleware('recent-auth')->name('partners.wallet.fund');
    Route::post('/partners/{partner:public_id}/settlements', [PartnerController::class, 'storeSettlement'])->middleware('recent-auth')->name('partners.settlements.store');
    Route::post('/settlements/{settlement:public_id}/approve', [PartnerController::class, 'approveSettlement'])->middleware('recent-auth')->name('settlements.approve');
    Route::post('/settlements/{settlement:public_id}/pay', [PartnerController::class, 'paySettlement'])->middleware('recent-auth')->name('settlements.pay');
    Route::get('/reports/finance', [ReportController::class, 'finance'])->name('reports.finance');
    Route::get('/reports/supplier-payables', [ReportController::class, 'supplierPayables'])->name('reports.supplier-payables');
    Route::get('/reports/operations', [ReportController::class, 'operations'])->name('reports.operations');
});
